from modeling.modeling_v1 import ElectraForMultipleChoicePlus
from modeling.modeling_v1 import RobertaForMultipleChoicePlus
from modeling.modeling_v1 import BertForMultipleChoicePlus
# from modeling.modeling_baseline import ElectraForMultipleChoicePlus as Baseline
# from modeling.modeling_baseline import BertForMultipleChoicePlus as BertBaseline
# from modeling.modeling_baseline import RobertaForMultipleChoicePlus as RobertaBaseline