python tune_MDFN.py \
--checkpoint output/output_mutual_electra_large/4_pytorch_model.bin \
--data_dir data/mutual \
--data_plus_dir data/mutual_plus \
--model_name_or_path google/electra-large-discriminator \
--model_type electra \
--task_name mutual \
--output_dir output/output_mutual_electra_large_plus \
--cache_dir cached_models \
--max_seq_length 256 \
--do_train \
--do_eval \
--train_batch_size 6 \
--eval_batch_size 6 \
--learning_rate 1e-6 \
--num_train_epochs 10 \
--gradient_accumulation_steps 3 \
--local_rank -1 \
--seed 123456